# https://taskfile.dev

version: "3"

vars:
  GREETING: Kindlib Repo Root

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  init-boot:
    desc: _
    cmds:
      - task install -d _infra/kindlib
