# https://taskfile.dev

version: "3"

vars:
  GREETING: Kindlib Repo Root

includes:
  kindlib: _infra/kindlib/task.kindlib.task.yml

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true

  install/kindlib-dyn:
    desc: install kindlib requirements
    cmds:
      - task kindlib:install -d _infra/kindlib

  install/kindlib-sta:
    desc: install kindlib requirements
    cmds:
      - task: kindlib:install
