# https://taskfile.dev

version: "3"

includes:
  kindlib: task.kindlib.task.yml

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true
